### ISSUE TITLE
Feature Request: Ability to select Tab on Split Screen Vertically/Horizontally buttons

### ISSUE THREAD

**Issue by lgastevens** [cbucher/console#170] opened 2015-01-25 17:32 UTC
Hi
Great tool. I use it all the time as a front end to an SSH/Telnet terminal I use.
The Split screen buttons are handy, though unfortunately they just clone a 2nd instance of whatever was already running in the starting Tab.
Would it be possible to have a pull down for the Split screen buttons (just as we have for the "New Tab" button) to allow selection of a different Tab profile to use in the new screen half ?

Many thanks
Ludovico Stevens

**Comment by cbucher** [comment] 2015-01-26 06:58
Hi

It is long-planned. But this requires separate shells and backgrounds. These are long and deep changes. And I lack of time and contributors.

I close this issue because this is a duplicate of #17.

**Closed by cbucher** 2015-01-26 06:58 UTC

**Comment by lgastevens** [comment] 2017-07-10 12:57
Hi
The referenced issue provided above, appears to be closed.
Is there really no plan to improve the split screen functionality ?
Some of the the functionality appears to be already there, in that I can edit a workspace file like this:
 <ConsoleZWorkspace>
     <Tab Title="VSP9000-1" Name="VSP9000">
           <SplitView Type="Vertical" Ratio="50">
                <Pane0>
                     <View Title="Tab-1"/>
                </Pane0>
                <Pane1>
                     <View Title="Tab-2"/>
                </Pane1>
           </SplitView>
     </Tab>
</ConsoleZWorkspace>

And then loading the workspace file yields the desired split screen with each side using the different Tab profile.
Would be nice to have a pull down on the split screen buttons to achieve the same.
Or else the ability to take 2 existing Tabs and have them merged into a split screen.
Best regards
Ludovico Stevens

**Comment by cbucher** [comment] 2017-07-10 13:10
>Or else the ability to take 2 existing Tabs and have them merged into a split screen.

Indeed, that is the solution I have chosen:
![image](https://user-images.githubusercontent.com/363759/28019501-75840612-6581-11e7-8476-1ec829c47569.png)

- create a new tab
- right click on unselected tab to merge into the selected tab

**Comment by lgastevens** [comment] 2017-07-11 07:13
Thanks, that is brilliant!
And I thought I had tried clicking everywhere...
Is it also possible to do the reverse ? I.e. restore the split views each back into its own Tab ?
Thanks
Best regards
Ludovico Stevens

**Comment by cbucher** [comment] 2017-07-11 10:02
That should be possible.
You can create a feature request.
