### ISSUE TITLE
Process leakage when opening vim causes msysgit bash shell to crash

### ISSUE THREAD

**Issue by dgoldstein0** [cbucher/console#280] opened 2015-10-19 22:32 UTC
I just installed Console today - liking it so far - but I seem to have found some unnatural ability to make it crash.  I haven't tweaked settings much yet, but the main thing I'm doing is using msysgit's bash as my shell - namely, `"C:\Program Files (x86)\Git\bin\bash.exe" --login -i` is my shell command, and it's running version 1.7.11-preview20120710 of it.  Now sometimes when I open a file in vim, like my _vimrc or a README, it for no obvious reason crashes the process (often with an alert about invalid memory access), and often I can repro this for a short time in a newly launched console process.  What's especially interesting is that when it crashes, it seems that `bash` is what's crashing, and moreover it leaks the vim process which somehow triggered the crash.  This is especially frustrating since not only it wastes memory (~1.3 MB - vim is light) but later attempts to access the same file run into it being already open by the orphaned process due to the swap file, which is not deleteable until the orphaned process is killed.

Anyhow I think this is a console bug because vim / bash seem extremely stable when run with the usual git bash shell gui - I never had problems with them crashing until today.  Happy to help troubleshoot as I know this info is rather incomplete.

**Comment by dgoldstein0** [comment] 2015-10-20 06:21
btw it looks like the most common crash is in trying to display the "there's a swap file" information.  Once there's a swap file, it seems to crash every time I try to open the corresponding file.

**Comment by dgoldstein0** [comment] 2015-10-20 07:15
I've reproed the swap file crash - it happens when a file has a corresponding swap file, but is NOT open by any program.  (Interestingly it's possible to crash and leak the vim process with the file open as well as for it to get into a situation where there's just a swap file, but not holding the file open.  If the file is open, the next vim process to come along will just open it read-only).

**Comment by dgoldstein0** [comment] 2015-10-20 07:16
oh and this crash does not occur under the normal msysgit bash gui.  So the shell seems to have something to do with it.

**Comment by cbucher** [comment] 2015-10-20 07:30
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

**Comment by dgoldstein0** [comment] 2015-10-20 07:52
Sorry, obviously didn't read that earlier.  I had ~10 crash files sitting around, but reproed it again for good measure.

Repro steps (with the msysgit bash shell, "C:\Program Files (x86)\Git\bin\bash.exe" --login -i)
- open a file in vim (e.g. a.txt)
- copy the swap file in another terminal / with explorer / whatever
- close vim.
- move the swap file to it's proper place (e.g. `.a.txt.swp`)
- `vim a.txt` -> crash

crashdump: https://www.dropbox.com/s/unyt0fhcym97rm1/bash.exe.10448.dmp?dl=0

**Comment by TheQwerty** [comment] 2015-10-20 11:42
@dgoldstein0 This is likely a dupe of issue #279.

I just tried your steps in a build (Release|x64) with commit 02dd0a77e4d9238ea82abdbb828a19e3dddfbc00 and it does not crash.

**Comment by dgoldstein0** [comment] 2015-10-22 09:48
mmm yeah, sounds very similar.  I installed the current stable build
(1.15.0.15253 x64).  Would love to take something newer for a spin, but
it's probably not going to be easy to compile from source - I don't have
the proper visual studio version, and have never gotten boost to work in
the past.  I'd rather not spend hours figuring out how to build it - could
you possibly provide a zip of the latest?

**Comment by TheQwerty** [comment] 2015-10-22 11:16
There's an experimental version that @cbucher built at the bottom of the [Downloads](https://github.com/cbucher/console/wiki/Downloads) page.

v1.16.0.15294 solved the issue I was seeing and doesn't crash when I follow your steps above.

**Comment by dgoldstein0** [comment] 2015-10-23 09:00
I remember trying that one before but having trouble extracting it.  Trying
again though, and I think I just borked the extraction command the first
time.  It seems to work just fine - can confirm the crash is fixed there.
Thanks for pointing me that direction!

**Closed** 2015-10-26 09:41 UTC
Labels: diagnostic report is missing
