### ISSUE TITLE
Repeated view splitting (+view navigation) using shortcuts causes glitches and crashes

### ISSUE THREAD

**Issue by youurayy** [cbucher/console#498] opened 2018-09-11 01:54 UTC
### Expected Behavior
Normal operation without glitches or crashes.

### Actual Behavior
Either of:
- The tab stops responding to any user input.
- The Alt+arrows combo to move between views stops working.
- The Ctrl+Shift+O combo starts typing ^O instead of opening new views.
- The tab stops responding to keyboard navigation between views (using Alt+arrows).
- User input is duplicated to all views in the tab. (this would be a cool feature actually)
- The program crashes (see attached dumps).

### Steps to reproduce
1. Start ConsoleZ and maximize it.
2. Create new views in the following pattern - create two columns with 4 equal-height rows: 
```
1. Ctrl+Shift+E
2. Ctrl+Shift+O * 2
3. Alt+UP *2
4. Ctrl+Shift+O
5. Alt+LEFT
6. Ctrl+Shift+O * 2
7. Alt+UP * 2,
8. Ctrl+Shift+O
9. if no crash at this point, press Ctrl+F1 (new tab) and repeat
```
3. Result: crash.

### Steps to reproduce (alternative)
1. Start ConsoleZ and maximize it.
2. Press Ctrl+Shift+O in quick succession (Hold Ctrl+Shift and keep pressing O quickly.)
3. Result: The Ctrl+Shift+O combo will start typing ^O instead of opening new views.

### Notes
- Tested with cmd.exe, but possibly easier to replicate/exhibit with a shell which is slower to initialize, e.g. Cygwin Bash.
- Tested on default config (no .xml in AppData).
- Tested on latest stable () and latest experimental (1.18.4.18221), Windows 10 x64 w/ latest updates 1803 (17134.1) (but has been happening for some time, possibly months, different (beefy) PCs and laptops).

### Temporary Workaround
~~Do not use keyboard shortcuts (default: Alt+arrows) when creating views by splitting (using Ctrl+Shift+E/O). Instead, use mouse/trackpad to change focus into newly created views, as needed. Create splits more slowly.~~
^doesn't work, the program then crashes when navigating between the splits using Alt+Arrows.

### Diagnostic Report
```
ConsoleZ aero amd64 1.18.3.18143
Windows 10 (64 bits) [10.0.17134]
is elevated? no
UAC prefix "Administrator: "
Tab (active): ConsoleZ
  View (active): 1. ConsoleZ
  is elevated? no
  input code page 437
  output code page 437
  Windows console font
font index: 0
face name: Consolas
font familly: 54 MODERN vector true type
font weight: 400
font size: width=7 height=16
max window size: cols=157 rows=86
  ConsoleZ font
GetFontLanguageInfo returns 262144.
The font contains extra glyphs not normally accessible using the code page.

  View: 1. ConsoleZ
  is elevated? no
  input code page 437
  output code page 437
  Windows console font
font index: 0
face name: Consolas
font familly: 54 MODERN vector true type
font weight: 400
font size: width=7 height=16
max window size: cols=157 rows=86
  ConsoleZ font
GetFontLanguageInfo returns 262144.
The font contains extra glyphs not normally accessible using the code page.

  View: 1. ConsoleZ
  is elevated? no
  input code page 437
  output code page 437
  Windows console font
font index: 0
face name: Consolas
font familly: 54 MODERN vector true type
font weight: 400
font size: width=7 height=16
max window size: cols=157 rows=86
  ConsoleZ font
GetFontLanguageInfo returns 262144.
The font contains extra glyphs not normally accessible using the code page.

  View: 1. ConsoleZ
  is elevated? no
  input code page 437
  output code page 437
  Windows console font
font index: 0
face name: Consolas
font familly: 54 MODERN vector true type
font weight: 400
font size: width=7 height=16
max window size: cols=157 rows=86
  ConsoleZ font
GetFontLanguageInfo returns 262144.
The font contains extra glyphs not normally accessible using the code page.

  View: 1. ConsoleZ
  is elevated? no
  input code page 437
  output code page 437
  Windows console font
font index: 0
face name: Consolas
font familly: 54 MODERN vector true type
font weight: 400
font size: width=7 height=16
max window size: cols=157 rows=86
  ConsoleZ font
GetFontLanguageInfo returns 262144.
The font contains extra glyphs not normally accessible using the code page.

  View: 1. ConsoleZ
  is elevated? no
  input code page 437
  output code page 437
  Windows console font
font index: 0
face name: Consolas
font familly: 54 MODERN vector true type
font weight: 400
font size: width=7 height=16
max window size: cols=157 rows=86
  ConsoleZ font
GetFontLanguageInfo returns 262144.
The font contains extra glyphs not normally accessible using the code page.

  View: 1. ConsoleZ
  is elevated? no
  input code page 437
  output code page 437
  Windows console font
font index: 0
face name: Consolas
font familly: 54 MODERN vector true type
font weight: 400
font size: width=7 height=16
max window size: cols=157 rows=86
  ConsoleZ font
GetFontLanguageInfo returns 262144.
The font contains extra glyphs not normally accessible using the code page.

  View: 1. ConsoleZ
  is elevated? no
  input code page 437
  output code page 437
  Windows console font
font index: 0
face name: Consolas
font familly: 54 MODERN vector true type
font weight: 400
font size: width=7 height=16
max window size: cols=157 rows=86
  ConsoleZ font
GetFontLanguageInfo returns 262144.
The font contains extra glyphs not normally accessible using the code page.

Tab: ConsoleZ
  View: 2. ConsoleZ
  is elevated? no
  input code page 437
  output code page 437
  Windows console font
font index: 0
face name: Consolas
font familly: 54 MODERN vector true type
font weight: 400
font size: width=7 height=16
max window size: cols=317 rows=86
  ConsoleZ font
GetFontLanguageInfo returns 262144.
The font contains extra glyphs not normally accessible using the code page.

  View (active): 2. ConsoleZ
  is elevated? no
  input code page 437
  output code page 437
  Windows console font
font index: 0
face name: Consolas
font familly: 54 MODERN vector true type
font weight: 400
font size: width=7 height=16
max window size: cols=317 rows=86
  ConsoleZ font
GetFontLanguageInfo returns 262144.
The font contains extra glyphs not normally accessible using the code page.
[CrashDumps.zip](https://github.com/cbucher/console/files/2368999/CrashDumps.zip)

  View: 2. ConsoleZ
  is elevated? no
  input code page 437
  output code page 437
  Windows console font
font index: 0
face name: Consolas
font familly: 54 MODERN vector true type
font weight: 400
font size: width=7 height=16
max window size: cols=317 rows=86
  ConsoleZ font
GetFontLanguageInfo returns 262144.
The font contains extra glyphs not normally accessible using the code page.

Monitors 1
+ Flags 1  primary
  DeviceID \\?\DISPLAY#SAM0E00#5&38bef9e2&0&UID4358#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
  DeviceKey \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
  DeviceName \\.\DISPLAY1\Monitor0
  DeviceString Generic PnP Monitor
  StateFlags 3
  Rect (0,0)x(3840,2160)
  Work (0,0)x(3840,2114)
  DPI (per monitor: yes) X=144 Y=144
System dpi 144
System metrics
  SM_CXSMICON        24
  SM_CYSMICON        24
  SM_CXICON          48
  SM_CYICON          48
  SM_CXVIRTUALSCREEN 3840
  SM_CYVIRTUALSCREEN 2160
  SM_CYVIRTUALSCREEN 2160
Settings file internal resource

```

### Crash Report
https://www.dropbox.com/sh/qxvejf3iz5dtjr5/AAC_MsZb9BW_tyqQxgCjF8H1a?dl=0

**Comment by youurayy** [comment] 2018-09-11 17:46
No, sorry, false positive, it's still definitely a problem.

**Comment by youurayy** [comment] 2018-09-11 17:50
1.18.2.17272 x64 seems to be okay

**Comment by cbucher** [comment] 2018-10-01 13:43
@youurayy 
Hi,

These are two unrelated problems .

I cannot reproduce crash. After dumps analysis, I added some tests in code to prevent the crash.
I don't understand how to enter in this state.
Say me if the last experimental version fix the problem.
https://github.com/cbucher/console/wiki/Downloads

If you see ^O, then input key Control-Shift-O has been sent to console.
[TranslateAccelerator ](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-translateacceleratorw)function detects hotkey when key is down.
[TranslateMessage ](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-translatemessage)function detects chars when key is up.
When you overload keyboard, you can stimulate the two functions.

**Comment by yanoryuichi** [comment] 2018-11-12 17:46
This happens in my environment. It looks to crash when I make a new view with CTRL-SHIFT+O and press ALT+UP or ALT+DOWN quickly.

**Comment by cbucher** [comment] 2018-11-16 11:42
@yanoryuichi Hi
Have you tried with last experimental version?
Can you provide crash dump ?
If you have Visual Studio/Spy++ tool, can you trace window messages ?

**Comment by cbucher** [comment] 2018-11-16 23:12
This issue should be fixed in last experimental version 1.18.4.18320.
https://github.com/cbucher/console/wiki/Downloads
A member variable was not initialized. I was able to reproduce by forcing a bad value.

**Comment by cbucher** [comment] 2018-12-06 21:16
@youurayy @yanoryuichi Can you test the fix in last experimental version ?

**Comment by cbucher** [comment] 2019-04-02 21:26
@youurayy Please try last beta version.
https://github.com/cbucher/console/wiki/Downloads

**Comment by cbucher** [comment] 2019-04-17 09:16
released

**Closed by cbucher** 2019-04-17 09:16 UTC
Labels: bug
