### ISSUE TITLE
Application crashes if closing a Console Window by double-clicking the window icon

### ISSUE THREAD

**Issue by mihaiolteanu** [cbucher/console#185] opened 2015-03-11 13:54 UTC
I have at least one tab open and visible. 

1. Right-click a tab and select Console Window
2. Double-click on the left window icon to close the window just opened from step 1
3. ConsoleZ crashes 

Windows 7 Enterprise, SP1
ConsoleZ 1.13.0.15044

**Comment by cbucher** [comment] 2015-03-12 11:44
I cannot reproduce the crash.
Please provide a crash dump and the diagnostic report (`Help/Diagnose`).

**Comment by mihaiolteanu** [comment] 2015-03-12 13:16
Actually, trying to access the Help/Diagnose produces another crash.
![consolez_crash](https://cloud.githubusercontent.com/assets/8273519/6618312/84bebd1c-c8ca-11e4-8355-5d34175bf9d9.PNG)
Any other way to retrieve the diag report?

**Comment by mihaiolteanu** [comment] 2015-03-12 13:55
I get these tmp files in the Temp folder every time it crashes:
*dmp6A27.tmp*, *dmpC542.tmp*, *dmpBFFD.tmp*, etc.. all containing the following:
`ConsoleZ aero amd64 1, 13, 0, 15044`

I've tried to reproduce the problem on another PC and it didn't reproduce. But, the application still crashed when I've tried to access the Help/Diagnose.

**Comment by cbucher** [comment] 2015-03-12 21:40
[experimental version 1.14.0.15071](https://dl.dumptruck.goldenfrog.com/p/MFMLht6iWV/ConsoleZ.1.14.0.15071.7z?dl=1)
I fixed the diagnostic creation.

To generate a crash dump, you can read [this documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181%28v=vs.85%29.aspx). If you didn't install a post mortem debugger, you should find crash dump here: `%LOCALAPPDATA%\CrashDumps`.

**Comment by mihaiolteanu** [comment] 2015-03-13 06:24
It still crashes on me on `Help/Diagnose`. 
On the other hand, I can't reproduce the issue in the experimental version you've attached here. I can, nonetheless, still reproduce the issue every time in the original version (15044). I've made the exact same settings in the experimental version as well.
I've already tried to reproduce this issue on two other PCs, but no "luck".

**Comment by cbucher** [comment] 2015-03-13 07:47
Create registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps` and provide crash dumps from `%LOCALAPPDATA%\CrashDumps`.

**Comment by mihaiolteanu** [comment] 2015-03-13 08:43
I only get crash dumps for the `Help/Diagnose` problem (exception code `0xC0000005`, `The thread tried to read from or write to a virtual address for which it does not have the appropriate access`). Do you want this crash dump? It's quite large (~90MB), so please let me know where to upload it.

The application is actually `Not Responding` when trying to close the window by double-clicking the window left icon. It only gives me the `Main ConsoleZ module has stopped working` (see the above screenshot) after I try closing it. Otherwise, it just "hangs" there, like this:
![not_responding](https://cloud.githubusercontent.com/assets/8273519/6635139/d12f5eb8-c96a-11e4-9991-9cf675d6a125.PNG)
...and I don't get any kind of crash dumps for this.

Also, this only happens when setting the tab with `C:\Program Files (x86)\Git\bin\sh.exe --login -i` [Using Git on Windows](http://wiki.dlang.org/Using_Git_on_Windows) in the Shell. I haven't tried other options here, but with an empty Shell field (so like a bare cmd.exe), it doesn't crash. This (bare cmd.exe) is what I've tested on the other two PCs that also didn't crash.

I've tried to make the ConsoleZ window as small as possible for the above screenshot so that it won't occupy too much space here. But then, I could not make it crash below a certain window size. And it seems that size is such that: if the new, detached "Console Window" overlaps the ConsoleZ and I try to close it by double-clicking the window icon, it crashes. Otherwise, it works fine.

**Comment by cbucher** [comment] 2015-03-13 09:41
Zip it and upload it to Dropbox, Google Drive, or a similar service, then post the link.

**Comment by cbucher** [comment] 2015-03-19 07:38
@mihaiolteanu Zip it and upload it to Dropbox, Google Drive, or a similar service, then post the link.

**Comment by cbucher** [comment] 2015-04-08 08:15
should be fixed with performances optimizations

**Closed by cbucher** 2015-04-08 08:15 UTC
Labels: timeout
